#!/bin/bash

cleaner () {
  sp=`ps -A | grep 'silk.jar -t preview' | grep -v grep | awk '{print $1}'`
  if [ $sp > 0 ]; then
    kill $sp
  fi
}

SK=$HOME/.silk
SKSP=$SK/repositories/site-prototype
SKC=$SK/repositories/component
if [ "$1" == "preview-start" ]; then
  cleaner
  java -jar $HOME/bin/silk.jar -t preview-start &
elif [ "$1" == "preview-stop" ]; then
  echo "Silk preview is stopped."
  cleaner
elif [ "$1" == "sites" ]; then
  echo "Installed site-prototypes are:"
  find $SKSP -type f -name dna.conf -exec grep 'id' {} \;
elif [ "$1" == "components" ]; then
  echo "Installed components are:"
  find $SKC -type f -name dna.conf -exec grep 'id' {} \;
elif [ "$1" == "update" ]; then
  mkdir -p $SK
  curl "http://www.bheap.co.uk/resource/downloads/silk/updates/0.1.0/silk.conf" \
          > $SK/silk.conf
	mkdir -p $SKSP
	curl "http://www.bheap.co.uk/resource/downloads/silk/updates/0.1.0/site-prototype.tgz" \
	        > site-prototype.tgz
	tar xf site-prototype.tgz -C $SKSP
	rm site-prototype.tgz
  mkdir -p $SKC
  curl "http://www.bheap.co.uk/resource/downloads/silk/updates/0.1.0/component.tgz" \
          > component.tgz
  tar xf component.tgz -C $SKC
  rm component.tgz
  echo "Silk update complete"
elif [ "$1" == "spin" ]; then
  rm -rf ${PWD}/site
  mkdir ${PWD}/site
  java -jar $HOME/bin/silk.jar -t $1 $2
else
  java -jar $HOME/bin/silk.jar -t $1 $2
fi

